# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gamemaster.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='gamemaster.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10gamemaster.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"g\n\x10PlayerIdentifier\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x1c\n\x14paddle_strategy_name\x18\x02 \x01(\t\x12 \n\x0bpaddle_type\x18\x03 \x01(\x0e\x32\x0b.PaddleType\"\x7f\n\tGameState\x12.\n\nstate_time\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fstate_iteration\x18\x02 \x01(\x04\x12)\n\x0ewinning_player\x18\x03 \x01(\x0b\x32\x11.PlayerIdentifier\"<\n\x0cPaddleAction\x12,\n\x11player_identifier\x18\x01 \x01(\x0b\x32\x11.PlayerIdentifier*.\n\nPaddleType\x12\x0b\n\x07NOT_SET\x10\x00\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x32\xc8\x01\n\nGameMaster\x12\x36\n\x11stream_game_state\x12\x11.PlayerIdentifier\x1a\n.GameState\"\x00\x30\x01\x12>\n\x0fregister_player\x12\x11.PlayerIdentifier\x1a\x16.google.protobuf.Empty\"\x00\x12\x42\n\x15submit_paddle_actions\x12\r.PaddleAction\x1a\x16.google.protobuf.Empty\"\x00(\x01\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])

_PADDLETYPE = _descriptor.EnumDescriptor(
  name='PaddleType',
  full_name='PaddleType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_SET', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=378,
  serialized_end=424,
)
_sym_db.RegisterEnumDescriptor(_PADDLETYPE)

PaddleType = enum_type_wrapper.EnumTypeWrapper(_PADDLETYPE)
NOT_SET = 0
LEFT = 1
RIGHT = 2



_PLAYERIDENTIFIER = _descriptor.Descriptor(
  name='PlayerIdentifier',
  full_name='PlayerIdentifier',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_name', full_name='PlayerIdentifier.player_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paddle_strategy_name', full_name='PlayerIdentifier.paddle_strategy_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='paddle_type', full_name='PlayerIdentifier.paddle_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=185,
)


_GAMESTATE = _descriptor.Descriptor(
  name='GameState',
  full_name='GameState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='state_time', full_name='GameState.state_time', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='state_iteration', full_name='GameState.state_iteration', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='winning_player', full_name='GameState.winning_player', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=314,
)


_PADDLEACTION = _descriptor.Descriptor(
  name='PaddleAction',
  full_name='PaddleAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_identifier', full_name='PaddleAction.player_identifier', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=376,
)

_PLAYERIDENTIFIER.fields_by_name['paddle_type'].enum_type = _PADDLETYPE
_GAMESTATE.fields_by_name['state_time'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_GAMESTATE.fields_by_name['winning_player'].message_type = _PLAYERIDENTIFIER
_PADDLEACTION.fields_by_name['player_identifier'].message_type = _PLAYERIDENTIFIER
DESCRIPTOR.message_types_by_name['PlayerIdentifier'] = _PLAYERIDENTIFIER
DESCRIPTOR.message_types_by_name['GameState'] = _GAMESTATE
DESCRIPTOR.message_types_by_name['PaddleAction'] = _PADDLEACTION
DESCRIPTOR.enum_types_by_name['PaddleType'] = _PADDLETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerIdentifier = _reflection.GeneratedProtocolMessageType('PlayerIdentifier', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERIDENTIFIER,
  __module__ = 'gamemaster_pb2'
  # @@protoc_insertion_point(class_scope:PlayerIdentifier)
  ))
_sym_db.RegisterMessage(PlayerIdentifier)

GameState = _reflection.GeneratedProtocolMessageType('GameState', (_message.Message,), dict(
  DESCRIPTOR = _GAMESTATE,
  __module__ = 'gamemaster_pb2'
  # @@protoc_insertion_point(class_scope:GameState)
  ))
_sym_db.RegisterMessage(GameState)

PaddleAction = _reflection.GeneratedProtocolMessageType('PaddleAction', (_message.Message,), dict(
  DESCRIPTOR = _PADDLEACTION,
  __module__ = 'gamemaster_pb2'
  # @@protoc_insertion_point(class_scope:PaddleAction)
  ))
_sym_db.RegisterMessage(PaddleAction)



_GAMEMASTER = _descriptor.ServiceDescriptor(
  name='GameMaster',
  full_name='GameMaster',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=427,
  serialized_end=627,
  methods=[
  _descriptor.MethodDescriptor(
    name='stream_game_state',
    full_name='GameMaster.stream_game_state',
    index=0,
    containing_service=None,
    input_type=_PLAYERIDENTIFIER,
    output_type=_GAMESTATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='register_player',
    full_name='GameMaster.register_player',
    index=1,
    containing_service=None,
    input_type=_PLAYERIDENTIFIER,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='submit_paddle_actions',
    full_name='GameMaster.submit_paddle_actions',
    index=2,
    containing_service=None,
    input_type=_PADDLEACTION,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GAMEMASTER)

DESCRIPTOR.services_by_name['GameMaster'] = _GAMEMASTER

# @@protoc_insertion_point(module_scope)
